version: 2

project_name: eban

builds:
  - id: eban
    main: ./cmd/eban
    binary: eban
    goos: [linux, windows]
    goarch: [amd64]
    flags: [-trimpath]
    ldflags: ["-s -w"]

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^chore:"]
